### ISSUE TITLE
THREE.WebGLProgram: gl.getProgramInfoLog() Warning on Latest Chrome, v 57

### ISSUE THREAD

**Issue by AlexanderPaule** [mrdoob/three.js#11138]
**##### Description of the problem** 

It is a few days I am observing a warning that is launched on Chrome. Initially I thought it was caused by my application, I was going to go crazy when I noticed that the same error occurs every time I start an application developed in Three.js, even those that worked perfectly. So I also checked the official on-line examples, such as "orbit control". In all cases I have the same error.

This error occurs when I open a new session of chrome and disappears when I update the page.
I tested the pages on all the computers at my rules and I got the same results.

I also tested the same pages on Firefox, but there no error is thrown.

**##### Screenshots**

New Chrome session open
[my application](http://www.appollo.altervista.org/errors/Immagine.png)
[orbit control](http://www.appollo.altervista.org/errors/Immagine12.png)
After reloading
[my application](http://www.appollo.altervista.org/errors/Immagine.png)

**##### Three.js version**

- [ ] Dev
- [x] r84
- [ ] ...

**##### Browser**

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

Chrome Version: 57.0.2987.133 (64-bit)

**##### OS**

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
I have intermittently seen this error recently, although I can't currently reproduce. I think something like this came up a while back and was caused by the error logging code not being strict enough and interpreting an invisible character as an error. Could something similar be happening here?

**Comment by jostschmithals** [comment]
I get the same warning (only) in Chrome **always** on the first load of an arbitrary threejs example (v84 or v85dev), if cache is disabled.

After reloading the warning is gone.

Chrome 57.0.2987.133 (Windows 10)

**Comment by AlexanderPaule** [comment]
I'm not sure, but I think it's something else, perhaps in the renderer. I built a [simple scene](http://www.appollo.altervista.org/errors/Immagine3.png) with just a BoxGeometry, but nothing change.

I also tried to use a line instead of the mesh, but have not been able to isolate the problem.
The warning is even launched.

**Comment by jostschmithals** [comment]
Just to clarify my previous comment: I'm getting the warning on first load (without caching) not only in the examples, but in every three.js application.

**Comment by AlexanderPaule** [comment]
Breaking News.
I understand the reason for failure.
In [WebGLProgram](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLProgram.js), at line 553, the comparsion return **true** because the **programLog** variable is not empty. It contains a string formed by [4 empty spaces](http://www.appollo.altervista.org/errors/Immagine4.png), so the warning is thrown.

I tried to take a look around the web to understand how the **WebGLRenderingContext.getProgramInfoLog()** work, but I haven not found the source code. Can someone post a link?

I find [this](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getProgramInfoLog), but there is no implementation.

**Comment by AlexanderPaule** [comment]
#9317

**Comment by mrdoob** [comment]
@kenrussell Seems like, since Chrome 57, `gl.getProgramInfoLog()` sometimes produce 4 empty lines?

**Comment by kenrussell** [comment]
@mrdoob please file a bug against Chrome with a test case and include about:gpu information from an affected system. Please send me the bug ID. Thanks.

**Comment by mrdoob** [comment]
@AlexanderPaule Could you file the bug on the Chrome Issue Tracker directly?
https://bugs.chromium.org/p/chromium/issues/list

**Comment by AlexanderPaule** [comment]
Done [ID - 711520](https://bugs.chromium.org/p/chromium/issues/detail?id=711520)

**Comment by kenrussell** [comment]
Thanks.

**Comment by Mardonis** [comment]
@AlexanderPaule any news this issue. Just saw the comments on the ticket not sure where they are on solving it. Just wandering. Thank you.

**Comment by AlexanderPaule** [comment]
I think they have not made any progress. 
I'll update you if there's any news.

**Comment by looeee** [comment]
I still experienced this yesterday, using Chrome Version 59.0.3071.29 (Official Build) beta (64-bit) on Windows 10.

It's intermittent and I have not found a way to reliably reproduce it though.

**Comment by dcyoung** [comment]
I am also seeing this warning running on electron v1.7.6 (chrome version 58.0.3029.110). Tested on both r85 or r87.  Issue was not present with electron v1.6.10 (chrome version 56.0.2924.87).

programLog is a string of length 4. Presumably empty lines.

**Comment by Mugen87** [comment]
As you can see [here](https://bugs.chromium.org/p/chromium/issues/detail?id=711520) it's still an open issue.

**Comment by Rolliboy** [comment]
Same problem on **r88** Firefox **56.0.2 (64 bit)**

**Comment by Itee** [comment]
Ah ah ah i see this warning from a while... i thought it was an expected behavior 😄 

So i got it under Windows 10 r89dev, chrome Version 62.0.3202.89 (Build officiel) (64 bits), Firefox 56.0.2 (64 bits) and 57.0 (64 bits).

Easy to reproduce under firefox typing on f5 and i got '\n\n\n' and not 4 spaces.

Under IE v11.674.15063.0, i was unable to got this error BUT i got 3 warnings about WebGLRender  (:grimacing:) ! May be the 3 EOL under the other browser ??? They are:

- THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.
- THREE.WebGLRenderer: OES_texture_half_float extension not supported.
- THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.

With Microsoft Edge 40.15063.674.0 nothing...

**Comment by mrdoob** [comment]
Closing, as this is a browser issue.

**Comment by Mugen87** [comment]
Should be solved with #12950
