### ISSUE TITLE
Unreal Bloom and Renderer Transparency issue

### ISSUE THREAD

**Issue by fire67** [mrdoob/three.js#14104]
##### Description of the problem
I am currently using the Unreal Bloom post with a transparent renderer.
```
renderer = new THREE.WebGLRenderer({ alpha: true });
renderer.setClearColor(0xFF0000, 0);
```
Unfortunately, the Unreal Bloom pass doesn't seem to take in account the alpha channel of the coming texture when doing the blur and it apparently comes from `getSeperableBlurMaterial` in _js\postprocessing\UnrealBloomPass.js_.

The fragment's alpha channel is always set to 1.0 which results in a complete removal of the previous alpha values when doing the additive blending at the end.

This is happening in the latest version of Three.js r92 and you can experiment about this issue using the [Unreal Bloom example](https://threejs.org/examples/?q=bloo#webgl_postprocessing_unreal_bloom)

**Comment by WestLangley** [comment]
In `getSeperableBlurMaterial()`you can try a work-around:
```javascript
gl_FragColor = vec4( diffuseSum / weightSum, 0.1 );\n\
```
Remember, it is an example, so you are free to modify it.

**Comment by fire67** [comment]
Thanks for the answer @WestLangley !
Yeah this would help keeping the transparency but would destroy the bloom effect (which is really cool btw) around the object. I think a more cleaner solution would be to apply weight on alpha channel too.

Any solution would help me a lot :)

**Comment by fire67** [comment]
I achieved to find a solution for this but I would love your opinion @spidersharma03 and @WestLangley.
```
void main()
{
	vec2 invSize = 1.0 / texSize;
	float fSigma = float(SIGMA);
	float weightSum = gaussianPdf(0.0, fSigma);
	float alphaSum = 0.0;
	vec3 diffuseSum = texture2D(colorTexture, vUv).rgb * weightSum;
	for( int i = 1; i < KERNEL_RADIUS; i ++ )
	{
		float x = float(i);
		float weight = gaussianPdf(x, fSigma);
		vec2 uvOffset = direction * invSize * x;
		
		vec4 sample1 = texture2D( colorTexture, vUv + uvOffset);
		float weightAlpha = sample1.a * weight;
		diffuseSum += sample1.rgb * weightAlpha;
		alphaSum += weightAlpha;
		weightSum += weight;
		
		vec4 sample2 = texture2D( colorTexture, vUv - uvOffset);
		weightAlpha = sample2.a * weight;
		diffuseSum += sample2.rgb * weightAlpha;
		alphaSum += weightAlpha;
		weightSum += weight;
		
	}
	alphaSum /= weightSum;
	diffuseSum /= alphaSum;
	gl_FragColor = vec4(diffuseSum.rgb, alphaSum);
}
```

**Comment by WestLangley** [comment]
Sorry, I have no opinion on this.

**Comment by spidersharma03** [comment]
Sorry @fire67 , was away for a few days. Yeah, what you have done seems correct. I didn't handle the transparency.

**Comment by fire67** [comment]
No problem, thank you for the answer @spidersharma03 !
While testing the effect I noticed a visual difference when pushing some values very high.

![bloom](https://user-images.githubusercontent.com/18648330/40599449-aad670a6-624d-11e8-9f97-3a596f28ded2.jpg)

Do you have any idea where does this comes from ?

**Comment by spidersharma03** [comment]
@fire67  , Not sure actually.  Do you have the changed code in some branch? I will try to take a look.
Thanks!

**Comment by fire67** [comment]
@spidersharma03 No, unfortunately the code is not available on a branch. Do you want me to do it ?
Just to let you know, there's nothing more than the main function in the previous post.

**Comment by jcyuan** [comment]
@spidersharma03 hi, I tried to use your `main()' code to replace the old one in example but all bloom effect gone although the background takes effect it's transparent.

`
    this.renderer = new THREE.WebGLRenderer({
            canvas: view,
            alpha:true
    });

    //and pass
    this.$unrealBloom = new UnrealBloomPass(new THREE.Vector2(this.app.stageWidth, this.app.stageHeight), 3.2, .6, 0.7 );
    this.$composer.addPass(this.$unrealBloom);
`

please help, thanks.

**Comment by robhawkes** [comment]
@fire67 Did you manage to get this working with the bloom keeping the colour of the object? As soon as I try to use the changed shader the bloom just goes pure white, rather than taking the object colour as before.

I also tried disabling `rendering.alpha` but the bloom was still pure white.

Any ideas?

```
void main() {\n\
  vec2 invSize = 1.0 / texSize;\
  float fSigma = float(SIGMA);\
  float weightSum = gaussianPdf(0.0, fSigma);\
  float alphaSum = 0.0;\
  vec3 diffuseSum = texture2D( colorTexture, vUv).rgb * weightSum;\
  for( int i = 1; i < KERNEL_RADIUS; i ++ ) {\
    float x = float(i);\
    float weight = gaussianPdf(x, fSigma);\
    vec2 uvOffset = direction * invSize * x;\
    vec4 sample1 = texture2D( colorTexture, vUv + uvOffset);\
    float weightAlpha = sample1.a * weight;\
    diffuseSum += sample1.rgb * weightAlpha;\
    alphaSum += weightAlpha;\
    weightSum += weight;\
    vec4 sample2 = texture2D( colorTexture, vUv - uvOffset);\
    weightAlpha = sample2.a * weight;\
    diffuseSum += sample2.rgb * weightAlpha;\
    alphaSum += weightAlpha;\
    weightSum += weight;\
  }\
  alphaSum /= weightSum;\
  diffuseSum /= alphaSum;\
  gl_FragColor = vec4(diffuseSum.rgb, alphaSum);\n\
}
```

Before:
![image](https://user-images.githubusercontent.com/22612/46878821-2641b480-ce3c-11e8-920e-7c97483b1168.png)

After:
![image](https://user-images.githubusercontent.com/22612/46878796-14f8a800-ce3c-11e8-82e2-bda34a73df1c.png)

**Comment by robhawkes** [comment]
I've been mulling this over for the past few days and decided to attempt a slightly different approach that takes the original (non-transparent) colour calculations, leaves them unmodified and then adds on top the new alpha calculations from @fire67 with a couple of minor tweaks to utilise the same weights as the colour calculations. I don't know if this is the right way to do it, and the calculations could probably be tidied up, but it works.

```
void main() {\n\
  vec2 invSize = 1.0 / texSize;\
  float fSigma = float(SIGMA);\
  float weightSum = gaussianPdf(0.0, fSigma);\
  float alphaSum = 0.0;\
  vec3 diffuseSum = texture2D( colorTexture, vUv).rgb * weightSum;\
  for( int i = 1; i < KERNEL_RADIUS; i ++ ) {\
    float x = float(i);\
    float w = gaussianPdf(x, fSigma);\
    vec2 uvOffset = direction * invSize * x;\
    vec4 sample1 = texture2D( colorTexture, vUv + uvOffset);\
    vec4 sample2 = texture2D( colorTexture, vUv - uvOffset);\
    diffuseSum += (sample1.rgb + sample2.rgb) * w;\
    weightSum += 2.0 * w;\
    float weightAlpha = sample1.a * w;\
    alphaSum += weightAlpha;\
    weightAlpha = sample2.a * w;\
    alphaSum += weightAlpha;\
  }\
  gl_FragColor = vec4(diffuseSum/weightSum, alphaSum/weightSum);\n\
}
```

Previous approach (posted earlier in this issue):

![](https://user-images.githubusercontent.com/22612/46878796-14f8a800-ce3c-11e8-82e2-bda34a73df1c.png)

New approach combining original logic with updated logic posted earlier in the issue:

![image](https://user-images.githubusercontent.com/22612/46922297-b7608900-cffe-11e8-9199-fc210903368e.png)

**Comment by robhawkes** [comment]
I've done some more testing and can confirm that the artefacts that I was seeing are unrelated to Three.js and the changes that I made to the bloom shader, so that's good.

**Comment by spidersharma03** [comment]
I will see the results with a colored scene and come back.

**Comment by spidersharma03** [comment]
@robhawkes , I see that you initialize the alphaSum to 0. Did you simply try making something like this::

`vec4 diffuseSum = texture2D( colorTexture, vUv)* weightSum;\
...
...
diffuseSum /= weightSum;`

**Comment by spidersharma03** [comment]
@robhawkes , basically something like this::

                                        float fSigma = float(SIGMA);
					float weightSum = gaussianPdf(0.0, fSigma);
					vec4 diffuseSum = texture2D( colorTexture, vUv) * weightSum;
					for( int i = 1; i < KERNEL_RADIUS; i ++ ) {
						float x = float(i);
						float w = gaussianPdf(x, fSigma);
						vec2 uvOffset = direction * invSize * x;
						vec4 sample1 = texture2D( colorTexture, vUv + uvOffset);
						vec4 sample2 = texture2D( colorTexture, vUv - uvOffset);
						diffuseSum += (sample1 + sample2) * w;
						weightSum += 2.0 * w;
					}
					gl_FragColor = vec4(diffuseSum/weightSum);

I need to test it though

**Comment by indivisualvj** [comment]
I've added this to the getCompmositeMaterial().fragmentShader. It reduces the bloom effect a little but gives me enough translucency to write and composite images over each other later:
```
float sum = col.r + col.g + col.b;
float opc = sqrt(sum/3.0);
gl_FragColor = vec4(col.rgb, opc);
```

**Comment by simongloor** [comment]
I tested the last two adjustments.

The version of @robhawkes turns grayscale in very bright areas.

The version of @spidersharma03 comes pretty close to the opaque version but doesn't look as good on the smoother gradients:
![Comparison](https://user-images.githubusercontent.com/43432178/55290999-4cebab80-53da-11e9-82ac-b461b12def2a.jpg)

**Comment by revyTH** [comment]
> Tidy things up a bit and it seems to work just as well:
> 
> ```
> void main() {\n\
>   vec2 invSize = 1.0 / texSize;\
>   float fSigma = float(SIGMA);\
>   float weightSum = gaussianPdf(0.0, fSigma);\
>   float alphaSum = 0.0;\
>   vec3 diffuseSum = texture2D( colorTexture, vUv).rgb * weightSum;\
>   for( int i = 1; i < KERNEL_RADIUS; i ++ ) {\
>     float x = float(i);\
>     float w = gaussianPdf(x, fSigma);\
>     vec2 uvOffset = direction * invSize * x;\
>     vec4 sample1 = texture2D( colorTexture, vUv + uvOffset);\
>     vec4 sample2 = texture2D( colorTexture, vUv - uvOffset);\
>     diffuseSum += (sample1.rgb + sample2.rgb) * w;\
>     alphaSum += (sample1.a + sample2.a) * w;\
>     weightSum += 2.0 * w;\
>   }\
>   gl_FragColor = vec4(diffuseSum/weightSum, alphaSum/weightSum);\n\
> }
> ```
> I've noticed some little (single pixel) artefacts that appear once in a while but seem to be random or based on something that only occurs on some frames as they disappear on the next frame. Not sure if it's caused by the changes I made or something unrelated to this issue.

Hi guys, after [changes from 101 to 102](https://github.com/mrdoob/three.js/wiki/Migration-Guide#r101--r102) it seems that the change on the fragment shader does not work anymore. Probably related to the change "Removed renderTarget and forceClear parameters from WebGLRenderer.render(). Please use .setRenderTarget() and .clear() instead before you perform the rendering. Be aware that it's now necessary to execute renderer.setRenderTarget( null ) in order to unset an active render target."

Any thought?

**Comment by robhawkes** [comment]
I'm slowly upgrading all my old experiments to work with r108 and after the comment by @revyTH I was worried my workaround for transparency in the bloom shader wasn't going to work any more. I'm unsure if something was actually broken with this in r102 but when I just added the same modified fragment shader I posted previously everything seems to work OK in r108.

For the avoidance of doubt, the background in the Three.js renderer in the screenshots is transparent, and overlaid over a Mapbox GL JS map. Without the modified fragment shader the bloom shader is opaque and you cannot see the map behind.

![2019-09-17 23_00_36-Window](https://user-images.githubusercontent.com/22612/65082997-4c060080-d99f-11e9-908b-8f5d891c1ebd.png)
![2019-09-17 23_00_20-Window](https://user-images.githubusercontent.com/22612/65083001-4e685a80-d99f-11e9-9aa0-869d63151776.png)

**Comment by robhawkes** [comment]
And for comparison, this is the same scene (slightly rotated) with the alternative approach suggest by @spidersharma03

![2019-09-17 23_09_49-Window](https://user-images.githubusercontent.com/22612/65083457-8623d200-d9a0-11e9-9390-39de402f3d5e.png)
![2019-09-17 23_09_36-Window](https://user-images.githubusercontent.com/22612/65083461-88862c00-d9a0-11e9-9831-dd7eea372df3.png)

**Comment by native1989** [comment]
@robhawkes Can you share this working example with mapbox map?

**Comment by fuzhenn** [comment]
I found a simpler solution: 

It doesn't need to take alpha into account during gaussian blur.
At the final step, when [combining bloom texture with the base texture](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_postprocessing_unreal_bloom_selective.html#L44), try to caculate an approximate alpha value for bloom rgb.

```glsl
void main() {
    vec4 baseColor = getTexture( baseTexture );
    vec3 bloom = getTexture( bloomTexture );
    //approximate alpha for bloom pixel when baseColor.a is 0 (transparent)
    //you can adjust it to make it more intense or softer
    float bloomAlpha = sqrt((bloom.r + bloom.g + bloom.b) / 3.0);
    //only use bloomAlpha when baseColor.a is 0
    float alpha = mix(bloomAlpha, baseColor.a, sign(baseColor.a));
    gl_FragColor = vec4(baseColor.rgb + bloom, alpha);

    // old code:
    // gl_FragColor = ( getTexture( baseTexture ) + vec4( 1.0 ) * getTexture( bloomTexture ) );
}
```
rendering result seems to be promising:

![image](https://user-images.githubusercontent.com/13678919/67754217-03973380-fa71-11e9-9937-42b2e046f108.png)

**Comment by valentincognito** [comment]
@fuzhenn That's the only modification you brought to the shader and you were able to set the renderer to alpha true and use a CSS background ?

**Comment by MagicBYang** [comment]
> I'm slowly upgrading all my old experiments to work with r108 and after the comment by @revyTH I was worried my workaround for transparency in the bloom shader wasn't going to work any more. I'm unsure if something was actually broken with this in r102 but when I just added the same modified fragment shader I posted previously everything seems to work OK in r108.
> 
> For the avoidance of doubt, the background in the Three.js renderer in the screenshots is transparent, and overlaid over a Mapbox GL JS map. Without the modified fragment shader the bloom shader is opaque and you cannot see the map behind.
> 
> ![2019-09-17 23_00_36-Window](https://user-images.githubusercontent.com/22612/65082997-4c060080-d99f-11e9-908b-8f5d891c1ebd.png)
> ![2019-09-17 23_00_20-Window](https://user-images.githubusercontent.com/22612/65083001-4e685a80-d99f-11e9-9aa0-869d63151776.png)

Thanks a lot for the mapbox example.
I try the same thing for a few days but always got a white untransparent scene above the mapbox map when I add your shader code.
So I guess the problem is the version of three.js. I tried r116dev and r108.r108 could not work at all 
with a total white scene.r116dev display like below:

![image](https://user-images.githubusercontent.com/29321723/79933441-99d96e80-8482-11ea-9556-8faee26a9788.png)

I stop render the unrealbloom pass the map show up again:
![image](https://user-images.githubusercontent.com/29321723/79933499-c7261c80-8482-11ea-9d53-cda5359da95f.png)

I can`t find what`s going on here if you still work in this field please show any clue to me if possible.
I saw a few similar issue in mapboxgl.js project too.

**Comment by gisonjourney** [comment]
> > I'm slowly upgrading all my old experiments to work with r108 and after the comment by @revyTH I was worried my workaround for transparency in the bloom shader wasn't going to work any more. I'm unsure if something was actually broken with this in r102 but when I just added the same modified fragment shader I posted previously everything seems to work OK in r108.
> > For the avoidance of doubt, the background in the Three.js renderer in the screenshots is transparent, and overlaid over a Mapbox GL JS map. Without the modified fragment shader the bloom shader is opaque and you cannot see the map behind.
> > ![2019-09-17 23_00_36-Window](https://user-images.githubusercontent.com/22612/65082997-4c060080-d99f-11e9-908b-8f5d891c1ebd.png)
> > ![2019-09-17 23_00_20-Window](https://user-images.githubusercontent.com/22612/65083001-4e685a80-d99f-11e9-9aa0-869d63151776.png)
> 
> Thanks a lot for the mapbox example.
> I try the same thing for a few days but always got a white untransparent scene above the mapbox map when I add your shader code.
> So I guess the problem is the version of three.js. I tried r116dev and r108.r108 could not work at all
> with a total white scene.r116dev display like below:
> 
> ![image](https://user-images.githubusercontent.com/29321723/79933441-99d96e80-8482-11ea-9556-8faee26a9788.png)
> 
> I stop render the unrealbloom pass the map show up again:
> ![image](https://user-images.githubusercontent.com/29321723/79933499-c7261c80-8482-11ea-9d53-cda5359da95f.png)
> 
> I can`t find what`s going on here if you still work in this field please show any clue to me if possible.
> I saw a few similar issue in mapboxgl.js project too.

hello,have you resolved this problem about unreal bloom of mapbox,can you give me some resolutions

**Comment by gisonjourney** [comment]
@robhawkes Can you share this working example with mapbox map?

**Comment by gisonjourney** [comment]
> @robhawkes Can you share this working example with mapbox map?

hi，do you have any solutions about mapbox to share with me

**Comment by luca-viggiani** [comment]
Hi, I see that this issue is still around since about three years and is now postponed to rXXX... Is there any workaround to use unrelabloom and keep canvas transparent background applicable to r127?

**Comment by bamboofx** [comment]
i got same problem to day.
What things i did and its work for me:

edit UnrealBloomPass.js 
`gl_FragColor = vec4(diffuseSum/weightSum, alphaSum/weightSum);`
set renderer clear color:
`renderer.setClearColor(0x000000, 0.0);`
add clearPass
`let clearPass = new ClearPass(0x000000, 0)`
set renderPass clear to false
`renderPass.clear = false`
Note: add pass correct order
`this.composer.addPass(clearPass);`
`this.composer.addPass(renderPass);`
` this.composer.addPass(unrealBloom); `

THREE r128

**Comment by luca-viggiani** [comment]
> i got same problem to day.
> What things i did and its work for me:
> 
> edit UnrealBloomPass.js
> 
> ```js
> gl_FragColor = vec4(diffuseSum/weightSum, alphaSum/weightSum);
> ```
> 
> set renderer clear color:
> 
> ```js
> renderer.setClearColor(0x000000, 0.0);
> ```
> 
> add clearPass
> 
> ```js
> let clearPass = new ClearPass(0x000000, 0)
> ```
> 
> set renderPass clear to false
> 
> ```js
> renderPass.clear = false
> ```
> 
> Note: add pass correct order
> 
> ```js
> this.composer.addPass(clearPass);
> this.composer.addPass(renderPass);
> this.composer.addPass(unrealBloom);
> ```
> 
> THREE r128

Hi, thanks for your suggestion, however the shader won't compile:

```
gl.getShaderInfoLog() fragment
ERROR: 0:196: 'alphaSum' : undeclared identifier
```

I guess there's something else to change in ```UnrealBloomPass.js```?

**Comment by mbalex99** [comment]
I've been following this thread for a while. Does anyone have a simple git repo of this? I'd love to learn but I need some substantial effort to port the code from an older version of ThreeJS. 

🙏

**Comment by lifund** [comment]
> I've created a full example. Thanks to help from: [#14104 (comment)](https://github.com/mrdoob/three.js/issues/14104#issuecomment-429664412)
> 
> Disclaimer it's in typescript:
> 
> * [Example](https://mbalex99.github.io/threejs-unrealbloompass-transparent-background-example/)
> * [Source Code](https://github.com/mbalex99/threejs-unrealbloompass-transparent-background-example)

Hi, 
Your fix worked great for me before, 
but when I added material.clippingPlanes to clip my objects,
somehow clipping directions are being messed up. 
( flipped, sometimes clipped object is half opaqe )

flipped problem for example, following code worked well alone, 

material.clippingPlanes = [
    new THREE.Plane( new THREE.Vector3( 1, 0, 0 ), 0 )
]

but with bloom it becomes like this.

material.clippingPlanes = [
    new THREE.Plane( new THREE.Vector3( -1, 0, 0 ), 0 )
]

**Comment by transitive-bullshit** [comment]
Confirming @mbalex99's solution works for me as well 💪 

Would it make sense to port this change back into the official example?

**Comment by mrdoob** [comment]
> Would it make sense to port this change back into the official example?

Feel free to give it a try 👍

**Comment by octaharon** [comment]
For anyone who's still struggling with this, I was able to achieve a similar (though not quite the same) result with original UnrealBloomPass by placing a ShaderPass on top of it with a makeshift transparency shader
`
	new ShaderMaterial({
		vertexShader: ColorifyShader.vertexShader,
		fragmentShader: glsl`

		uniform float transparency;
		uniform sampler2D tDiffuse;

		varying vec2 vUv;

		void main() {

			vec4 texel = texture2D( tDiffuse, vUv );

			vec3 luma = vec3(0.33, 0.33, 0.33);
			float v = pow(dot( texel.rgb, luma ), 0.05); // the expontent can be parametrized to adjust brightness
			gl_FragColor = vec4( texel.rgb, texel.a*v*transparency );
		}
		`,
		transparent: true,
		blending: AdditiveBlending,
		uniforms: {
			transparency: { value: 1}, // can be parametrized as well
		},
`

this probably will be undesireable though, if the UnrealBloomPass is not the final shader in the chain

**Comment by netgfx** [comment]
Is there any ports in r3f for the 

> I've created a full example. Thanks to help from: [#14104 (comment)](https://github.com/mrdoob/three.js/issues/14104#issuecomment-429664412)
> 
> Disclaimer it's in typescript:
> 
> * [Example](https://mbalex99.github.io/threejs-unrealbloompass-transparent-background-example/)
> * [Source Code](https://github.com/mbalex99/threejs-unrealbloompass-transparent-background-example)

Any idea if this exists for r3f or is there another way to achieve transparent background and bloom effect in r3f nowadays?

**Comment by manmohanbishnoi** [comment]
> I've created a full example. Thanks to help from: [#14104 (comment)](https://github.com/mrdoob/three.js/issues/14104#issuecomment-429664412)
> 
> Disclaimer it's in typescript:
> 
> * [Example](https://mbalex99.github.io/threejs-unrealbloompass-transparent-background-example/)
> * [Source Code](https://github.com/mbalex99/threejs-unrealbloompass-transparent-background-example)

Solution provided by @mbalex99 worked for me with r136

**Comment by DOSputin** [comment]
_Typescript_ 🤢
Reverted  @mbalex99's implementation back to pure JS and it does work fine with alpha, also on with r136

**Comment by mrdoob** [comment]
> Reverted @mbalex99's implementation back to pure JS and it does work fine with alpha, also r136

Lovely! Could you share the JS version? 🤓

**Comment by DOSputin** [comment]
> > Reverted @mbalex99's implementation back to pure JS and it does work fine with alpha, also r136
> 
> Lovely! Could you share the JS version? 🤓

I'm sort of new here in the Three.js scene.  How would you suggest might be the best way to share?  As in, what's the preference?

**Comment by DOSputin** [comment]
@mrdoob; I uploaded my JS version in this gist: [https://gist.github.com/DOSputin/3bcb7355cbb2aef87013dbacb33ec2e1](UnrealBloomPassAlpha.js) since I'm not sure what the proper procedure to follow for doing a PR would be.  Should these changes be integrated into the original **UnrealBloomPass** and do a #14104 branch PR?

**Comment by mrdoob** [comment]
A new PR would be great actually.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by VanderSP** [comment]
tried pasting the code on node_modules, and re run npm run dev... with original mbalex99 code i got the alpha.. with this version i got black background (im using 2 canvas layer)

**Comment by VanderSP** [comment]
Okay, i´ve found what happens ->

the bloom alpha was finally fixed on 137.5
the bloom alpha fix was broken in 137.3

i tested in 137.2 and 136.0 it worked (pasting the file on node_modules)

**Comment by Mugen87** [comment]
I've decided to having a look at this issue since the PR #23356 does not solve this issue to me. Here is my branch with the suggested change from above: https://github.com/Mugen87/three.js/commit/551e7b5640b76e0e966b40e1cf9b2a1cb7122e95

`UnrealBloomPass` now supports transparent backgrounds however the bloom does not blend correctly with the HTML background image. The same artifacts appear like mentioned in https://github.com/mrdoob/three.js/issues/14104#issuecomment-478351541 (see the three screenshots at the end of the post).

You can easily verify this by opening the following URL and set the bloom strength and radius to maximum.

https://raw.githack.com/Mugen87/three.js/dev60/examples/webgl_postprocessing_unreal_bloom.html

Looking at the suggested fix, a simple enhancement in the fragment shader is not sufficient.

**Comment by Mugen87** [comment]
>  the bloom does not blend correctly with the HTML background image.

After some research it seems this issue can't be solved. Bloom needs to be additively blended with whatever is behind it. However, the default blending of the WebGL canvas and the HTML background is `GL_ONE, GL_ONE_MINUS_SOURCE_ALPHA` (that is corresponds to `NormalBlending` in `three.js`). And as far as I know it is not possible to change the browser default.

For a correct blending with the HTML background, the pass also has to honor premultiplied alpha which is currently not true.

@greggman I have seen that you answered related questions at stackoverflow. Can you confirm that the preconditions of the browser blending process is fixed (premultiplied alpha + `GL_ONE, GL_ONE_MINUS_SOURCE_ALPHA`)?

**Comment by luca-viggiani** [comment]
Hi, I've been using [this tweak](https://github.com/mrdoob/three.js/issues/14104#issuecomment-429664412) with `128` and worked for long time very well.
Today I switched to `142` and the tweak doesn't work anymore. I looked at comment above and saw that the issue should be fixed in `137.5` so I removed the tweak from my code but it still renders a black background with `142`.
Here is my code:

```javascript
const BLOOM_PARAMS = {
    resolution: new THREE.Vector2(1024, 1024),
    strength: 2,
    radius: .65,
    threshold: .85
}

const CAMERA_PARAMS = {
    fov: 50,
    pixelRatio: window.devicePixelRatio,
    nearClippingPlane: .1,
    farClippingPlane: 10000
}

this.#scene = new THREE.Scene();
this.#renderer = new THREE.WebGLRenderer({
    antialias: true,
    alpha: true,
    format: THREE.RGBAFormat,
    logarithmicDepthBuffer: true
});

this.#renderer.shadowMap.type = THREE.PCFSoftShadowMap;
this.#renderer.outputEncoding = THREE.sRGBEncoding;
this.#renderer.setPixelRatio(window.devicePixelRatio);
this.#renderer.setClearColor(0x000000, 0.0);

this.#shadowRoot.appendChild(this.#renderer.domElement);

this.#camera = new THREE.PerspectiveCamera(...Object.values(CAMERA_PARAMS));

this.#passes = {
    render: new RenderPass(this.#scene, this.#camera),
    bloom: new UnrealBloomPass(...Object.values(BLOOM_PARAMS))
}

this.#effectComposer = new EffectComposer(this.#renderer);
Object.values(this.#passes).forEach(pass => this.#effectComposer.addPass(pass));
```

Where I do wrong? Thanks!

**Comment by Mugen87** [comment]
> saw that the issue should be fixed in 137.5

The issue is actually not fixed. Sorry for the confusion in this topic.

Besides, I don't think the issue _can_ be properly fixed since there is no way to correctly additively blend the bloom with a HTML background.

I think we should close the issue and state that `UnrealBloomPass` requires a non-transparent background.

**Comment by lviggiani** [comment]
Ok, the mix doesn't work. I'll stick to 128 + frag shader for now

**Comment by CountAsWun** [comment]
Ah i was so hopeful when i saw that this was fixed but maybe we are back at square one.  I don't know much about modifying this library and the underlying WebGL tech but i've spent 10 hours trying to get background transparency working as it is essential to my use case.  

What changed from the previous versions that now break background transparency?

What is it about RenderPass that handles background transparency with ease that breaks in UnrealBloom?

**Comment by johnnyshankman** [comment]
+1 Why haven't we fixed this?

**Comment by johnnyshankman** [comment]
Also what is up with the breaking changes from 127 to 128? Codepen: https://codepen.io/johnnyshankman/pen/MWGMqYZ I can't seem to figure out how to upgrade to 128 successfully.

**Comment by donmccurdy** [comment]
@johnnyshankman I'd recommend using the forums (https://discourse.threejs.org/) for help with the upgrade to r128. 

This remains open because no working, stable fix has been found. You might try https://github.com/pmndrs/postprocessing/, it may support bloom + canvas transparency.

**Comment by Mugen87** [comment]
Voting again for closing this issue since I don't think it can be fixed, see https://github.com/mrdoob/three.js/issues/14104#issuecomment-1180499097.

**Comment by xiaohaook** [comment]
//fragmentShader
     void main() {
					vec2 invSize = 1.0 / texSize;
					float fSigma = float(SIGMA);
					float alphaNum = 0.0; 
					float weightSum = gaussianPdf(0.0, fSigma);
					vec3 diffuseSum = texture2D( colorTexture, vUv).rgb * weightSum;
					for( int i = 1; i < KERNEL_RADIUS; i ++ ) {
						float x = float(i);
						float w = gaussianPdf(x, fSigma);
						vec2 uvOffset = direction * invSize * x;
						vec3 sample1 = texture2D( colorTexture, vUv + uvOffset).rgb;
						vec3 sample2 = texture2D( colorTexture, vUv - uvOffset).rgb;
						diffuseSum += (sample1 + sample2) * w;
						weightSum += 2.0 * w;
						alphaNum += (texture2D( colorTexture, vUv + uvOffset).a + texture2D( colorTexture, vUv - uvOffset).a) * w;
					}
		             
					gl_FragColor = vec4(diffuseSum/weightSum, alphaNum/weightSum);
				}


    //212 line
    render( renderer, writeBuffer, readBuffer, deltaTime, maskActive ) {

		renderer.getClearColor( this._oldClearColor );
		this.oldClearAlpha = renderer.getClearAlpha();
		const oldAutoClear = renderer.autoClear;
		renderer.autoClear = false;

		renderer.setClearColor( this.clearColor, 0 );

		if ( maskActive ) renderer.state.buffers.stencil.setTest( false );



		if ( this.renderToScreen ) {

			this.fsQuad.material = this.basic;
			this.basic.map = readBuffer.texture;

			renderer.setRenderTarget( null );
			//Todo
			renderer.clear(false,true,true);
			//this.fsQuad.render( renderer );

		}


![AA769955-450E-4208-B62A-4EFF16B62B96](https://user-images.githubusercontent.com/19567662/199913341-0ffc3cfe-3c1f-4259-ba62-cbe67f798981.png)
![52E94636-F8DA-4000-BE2F-64B40A67F526](https://user-images.githubusercontent.com/19567662/199913379-a6e20b83-3b44-42d8-9d77-d261c2616ffd.png)


The three version is 0.146.0
This is the effect before I changed UnrealBloomPass.js. The background is opaque. To make the background transparent, I modified the code of the slice source shader in UnrealBloomPass.js, but it cannot make my scene transparent. So I changed renderer. clear() to renderer clear(false,true,true); And commented out this.fsQuad render( renderer );
The display is as follows. The background is transparent, but the display is very false. I need official help

**Comment by donmccurdy** [comment]
@xiaohaook — please use other channels for help, such as the forums (https://discourse.threejs.org/). We do not provide support in github issues.

**Comment by ButzYung** [comment]
@Mugen87  Recently I tried to implement UnrealBloom in my app but encountered the same transparency problem. I came across this thread, seeing all attempts to modify the blur pass in the middle but none seemed to yield favorable results. After trying some experiments by myself, I suggest a new approach which basically doesn't need to modify UnrealBloom.js.

I use the [selective bloom example](https://threejs.org/examples/?q=bloo#webgl_postprocessing_unreal_bloom_selective) as a base. In the fragment shader of the final pass where the bloom texture and the screen texture is merged,

`gl_FragColor = ( texture2D( baseTexture, vUv ) + vec4( 1.0 ) * texture2D( bloomTexture, vUv ) );`

which is practically a simple additive operation, I replace it with the following.

```
vec4 base_color = texture2D(baseTexture, vUv);
vec4 bloom_color = texture2D(bloomTexture, vUv);

float lum = 0.21 * bloom_color.r + 0.71 * bloom_color.g + 0.07 * bloom_color.b;
gl_FragColor = mix(vec4(bloom_color.rgb, lum), base_color + bloom_color, base_color.a);
```

The concept is faily simple. I generate an alpha value for the final bloom texture by using its luminosity as a base (it can be something else other than luminosity, which is open for discussion). The final result is a mix of this new bloom value and the original `base_color+bloom_color`, based on the alpha of `base_color`. For fully opaque parts, the result is completely identical with the default approach. For the transparent parts, it will be the new transparent bloom value.

The actual result is fairly decent, at least according to my testings. Below are some screenshots using the same bloom parameters. As you can see, the default one with no transparency (i.e. black background) looks almost identical with the new approach using a HTML black background.

![_bloom00](https://user-images.githubusercontent.com/3256084/236523685-99092a1b-0ac1-4e33-b706-e5bbc873bfe1.png)
![_bloom01](https://user-images.githubusercontent.com/3256084/236523783-1e45ef47-3acf-418e-89ad-0fe346beee63.png)

The new approach also looks fairly decent on a pure white background, as well as a complex background.

![_bloom02](https://user-images.githubusercontent.com/3256084/236523851-cc911f5d-acb5-41b4-9ab2-eb2810448bed.png)
![_bloom03](https://user-images.githubusercontent.com/3256084/236523914-78070066-3311-406e-aaee-799abfe1190b.png)

Of course, this is not a perfect solution. There is no perfect solution when there is no way to actually mix WebGL with HTML background with additive blending. At least, this is a fairly reasonable solution for those who really needs a transparent background.

**Comment by simongloor** [comment]
Wow, the result is amazing, congratz!

**Comment by jscottk** [comment]
I was able to get this working using the UnrealBloomPass with the EffectComposer by updating the getSeparableBlurMaterial function to use vec4 instead of vec3 for diffuseSum, sample1, and sample2, and instead of sampling just rgb, I sampled alpha as well (rgba), like: 

getSeperableBlurMaterial( kernelRadius ) {

		return new ShaderMaterial( {

			defines: {
				'KERNEL_RADIUS': kernelRadius,
				'SIGMA': kernelRadius
			},

			uniforms: {
				'colorTexture': { value: null },
				'texSize': { value: new Vector2( 0.5, 0.5 ) },
				'direction': { value: new Vector2( 0.5, 0.5 ) }
			},

			vertexShader:
				`varying vec2 vUv;
				void main() {
					vUv = uv;
					gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );
				}`,

			fragmentShader:
				`#include <common>
				varying vec2 vUv;
				uniform sampler2D colorTexture;
				uniform vec2 texSize;
				uniform vec2 direction;

				float gaussianPdf(in float x, in float sigma) {
					return 0.39894 * exp( -0.5 * x * x/( sigma * sigma))/sigma;
				}
				void main() {
					vec2 invSize = 1.0 / texSize;
					float fSigma = float(SIGMA);
					float weightSum = gaussianPdf(0.0, fSigma);
					vec4 diffuseSum = texture2D( colorTexture, vUv).rgba * weightSum;
					for( int i = 1; i < KERNEL_RADIUS; i ++ ) {
						float x = float(i);
						float w = gaussianPdf(x, fSigma);
						vec2 uvOffset = direction * invSize * x;
						vec4 sample1 = texture2D( colorTexture, vUv + uvOffset).rgba;
						vec4 sample2 = texture2D( colorTexture, vUv - uvOffset).rgba;
						diffuseSum += (sample1 + sample2) * w;
						weightSum += 2.0 * w;
					}
					vec4 background = texture2D( colorTexture, vUv );
					gl_FragColor = vec4(diffuseSum/weightSum);
				}`
		} );

	}

**Comment by fermmm** [comment]
> @Mugen87 Recently I tried to implement UnrealBloom in my app but encountered the same transparency problem. I came across this thread, seeing all attempts to modify the blur pass in the middle but none seemed to yield favorable results. After trying some experiments by myself, I suggest a new approach which basically doesn't need to modify UnrealBloom.js.
> 
> I use the [selective bloom example](https://threejs.org/examples/?q=bloo#webgl_postprocessing_unreal_bloom_selective) as a base. In the fragment shader of the final pass where the bloom texture and the screen texture is merged,
> 
> `gl_FragColor = ( texture2D( baseTexture, vUv ) + vec4( 1.0 ) * texture2D( bloomTexture, vUv ) );`
> 
> which is practically a simple additive operation, I replace it with the following.
> 
> ```
> vec4 base_color = texture2D(baseTexture, vUv);
> vec4 bloom_color = texture2D(bloomTexture, vUv);
> 
> float lum = 0.21 * bloom_color.r + 0.71 * bloom_color.g + 0.07 * bloom_color.b;
> gl_FragColor = vec4(base_color.rgb + bloom_color.rgb, max(base_color.a, lum));
> ```
> 
> The concept is fairly simple. I generate an alpha value for the final bloom texture by using its luminosity as a base (it can be something else other than luminosity, which is open for discussion). The final result is the original `base_color + bloom_color` as color, plus the max of `base_color.a` and the new bloom alpha as the final alpha. For fully opaque parts, the result is completely the same as the default approach.
> 
> The actual result is fairly decent, at least according to my testings. Below are some screenshots using the same bloom parameters. As you can see, the default one with no transparency (i.e. black background) looks almost identical with the new approach using a HTML black background.
> 
> ![_bloom00](https://user-images.githubusercontent.com/3256084/236523685-99092a1b-0ac1-4e33-b706-e5bbc873bfe1.png) ![_bloom01](https://user-images.githubusercontent.com/3256084/236540705-de4a40f2-d841-48b8-b904-885b9228abdb.png)
> 
> The new approach also looks fairly decent on a pure white background, as well as a complex background.
> 
> ![_bloom02](https://user-images.githubusercontent.com/3256084/236540753-22143418-0053-4c28-b555-06a2d09004bc.png) ![_bloom03](https://user-images.githubusercontent.com/3256084/236540824-86f1f9c0-e2e6-47f0-b495-a20a8ceef19d.png)
> 
> Of course, this is not a perfect solution. There is no perfect solution when there is no way to actually mix WebGL with HTML background with additive blending. At least, this is a fairly reasonable solution for those who really needs a transparent background.

cool but it looks bad on dark backgrounds

**Comment by kristiker** [comment]
We got this working, for some reson `tDiffuse` input in `bloomPass.blendMaterial` has non-zero alpha in the whole texture, despite there being bloom or not.

On areas with no bloom it would go like this:
rgb = vec3(0, 0, 0)
alpha = 0.3; 
AdditiveBlending -> causes background to darken

In fragment shader, after:
`vec4 texel = texture2D( tDiffuse, vUv );`

add
```
float flFactor = length(texel.rgb) * 5.0; // could find a better formula
texel.a = mix(0.0, texel.a, flFactor);
````

After this bloom works pretty well with a full transparent renderer.
