### ISSUE TITLE
ColladaLoader: Malformed urls

### ISSUE THREAD

**Issue by martin-yanakiev** [mrdoob/three.js#19345]
I'm loading dae via http url, the dae and all of its textures are accessed like wise:
```
http://<baseurl>/<relative path>/name.dae
http://<baseurl>/<relative path>/TextureResource1.png
http://<baseurl>/<relative path>/TextureResource2.png
```

All textures in the dae are references like:

```
<image id = "TextureResource1img">
<init_from>./TextureResource1.jpg</init_from>
</image>
<image id = "TextureResource2img">
<init_from>./TextureResource2.jpg</init_from>
```

I use ColladaLoader to load dae with relative url like `"/<relative path>/name.dae"`

1. When I pass this line:

	`var path = (scope.path === '') ? core_js_libs_threejs1_three_module_js__WEBPACK_IMPORTED_MODULE_0__["LoaderUtils"].extractUrlBase(url) : scope.path;`

	path is set to `"/<relative path>/"`

2. Then in ColladaLoader.parse you create a texture loader and set it's path to `"/<relative path>/"`

	`textureLoader.setPath(this.resourcePath || path).setCrossOrigin(this.crossOrigin);`

3. In the process of loading the textures you are calling loatTextureForUniform, there

`var image = getImage(surface.init_from);`

is set to `"./TextureResource1.jpg"`

since I have path set to `"/<relative path>/"`, I get in the if

```
if (path) {
	var parts = path.split('/');
	parts.pop();
	let baseUrl = (parts.length < 1 ? '.' : parts.join('/')) + '/';
	url = baseUrl + image;
}
```

as a result I get url set to `"/<relative path>/./TextureResource1.jpg"`

Which btw is still fine by the browser since If you call it like this, the browser resolves the relative path to absolute by itself, but you do not stop here!

4. While makeing this call:

`var texture = getTextureLoader(url).load(url);`

I end up in ImageLoader.load with url `"/<relative path>/./TextureResource1.jpg"` and `this.path = "/<relative path>/"` and this IF kills it:

`if ( this.path !== undefined ) url = this.path + url;`

The result is url `"/<relative path>//<relative path>/./TextureResource1.jpg"`?

**Comment by martin-yanakiev** [comment]
Since TextureLoader uses ImageLoader it is right to say first is the host loader. I think this issue may happen to other loaders that have the same relation, since you are passing the path from loader to loader. So I see two solutions.

1. When the host loader is calling load on the inner loader it should pass information if the url is already concatenated.

2. What I find better approach is additional url object that holds that information in itself.

I want to fix it for myself until official fix is released, so just asking if I'm getting the problem right and if those solutions (1 or 2) will not break otger logics?

**Comment by Mugen87** [comment]
TBH, I still don't understand what the problem is. The internal `TextureLoader` is configured via `setPath()`. 

https://github.com/mrdoob/three.js/blob/8b96a9986f911a61493f2db0be2d25279bbc42c2/examples/jsm/loaders/ColladaLoader.js#L3917

The call of `load()` is done with the image name in the `Collada` file.

https://github.com/mrdoob/three.js/blob/8b96a9986f911a61493f2db0be2d25279bbc42c2/examples/jsm/loaders/ColladaLoader.js#L1569

Can you please show the code where the path is added twice? It seems this is the problem you wanted to report, right?

**Comment by martin-yanakiev** [comment]
Hello, @Mugen87 this is the code

`if ( this.path !== undefined ) url = this.path + url;`

It is in ImageLoader.load() at this point path is  `"/<relative path>/"` and url is `"/<relative path>/./TextureResource1.jpg"`

After the if they are concatenated.

**Comment by Mugen87** [comment]
> url is "/<relative path>/./TextureResource1.jpg"

Can you please explain once more why this URL is given to `ImageLoader`? When reading the code in `ColladaLoader`, it looks like the loader directly passes the image name to the `load()` method (without modification).

BTW: Instead of copy/paste code, you can also link to source files like I did in my post before.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：martin-yanakiev <notifications@github.com>
发送时间：2020-05-13 16:54
主题：Re: [mrdoob/three.js] ColladaLoader: Malformed urls (#19345)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Hello, @Mugen87 this is the code
if ( this.path !== undefined ) url = this.path + url;
It is in ImageLoader.load() at this point path is "/<relative path>/" and url is "/<relative path>/./TextureResource1.jpg"
After the if they are concatenated.

**Comment by Mugen87** [comment]
Closing due to lack of feedback.

Please share a working demo (e.g. as a live example or a GitHub repo) that demonstrates the issue.
