### ISSUE TITLE
WebXR VR Examples are broken since the v130 update on Oculus Quest 2

### ISSUE THREAD

**Issue by dbradleyfl** [mrdoob/three.js#22069]
**Describe the bug**

A bunch of the three js examples for VR no longer work since v130 and we're seeing the same issue in our application when we upgrade to v130.

**To Reproduce**

1. It may require testing a layers enabled example first (or not)
2. Try the following examples:
  - https://threejs.org/examples/?q=webxr#webxr_vr_ballshooter
  - https://threejs.org/examples/?q=webxr#webxr_vr_cubes
  - https://threejs.org/examples/?q=webxr#webxr_vr_panorama
  - https://threejs.org/examples/?q=webxr#webxr_vr_panorama_depth
  - https://threejs.org/examples/?q=webxr#webxr_vr_paint
  - https://threejs.org/examples/?q=webxr#webxr_vr_rollercoaster
  - https://threejs.org/examples/?q=webxr#webxr_vr_sculpt
  - https://threejs.org/examples/?q=webxr#webxr_vr_video

**Expected behavior**

The demos should function as they did before, but currently they just show up totally black in the headset.

**Platform:**

 - Device:  Oculus Quest 2
 - OS:  v30.1
 - Browser: Oculus Quest Browser
 - Three.js version: 130

**Comment by dbradleyfl** [comment]
Using the webxr_vr_panorama as an example I found two things that "fix" the example.

1. It seems to be essential that the renderer has shadowMap true 
![image](https://user-images.githubusercontent.com/5935459/124061781-5febec80-d9e4-11eb-801a-297d8669c4c6.png)

2. It also seems to be essential that the scene have a light that casts shadows:
![image](https://user-images.githubusercontent.com/5935459/124061864-8578f600-d9e4-11eb-9461-601796afcc97.png)

I don't think those new requirements are intentional.

**Comment by marcofugaro** [comment]
May be the same issue of https://github.com/mrdoob/three.js/pull/22060#issuecomment-870653317?

**Comment by Mugen87** [comment]
I can't reproduce on a Quest 2 with latest Oculus Browser. Is it possible that your browser is not up-to-date?

**Comment by cabanier** [comment]
These used to work on my quest. I suspect I broke something up while fixing the multiple render target problem.

**Comment by arpu** [comment]
@cabanier  latest OculusBrowser update from 8h breaks vrland.io too, works bevore the Browser update yesterday

**Comment by cabanier** [comment]
@arpu , did you pick up a new three.js or is it just broken?

**Comment by arpu** [comment]
tested yesterday threejs 130 and all works, after todays browser update its just broken

**Comment by cabanier** [comment]
> tested yesterday threejs 130 and all works, after todays browser update its just broken

If it breaks with a new browser and an old three.js, that sounds like another issue in the browser.
What happens if you disable WebXR Layers in chrome://flags? Is it still broken?

**Comment by arpu** [comment]
yes disable Webxr Layers in the chrome flags fixed the issue and i can enter webxr mode on vrland.io and threejs officiell samples

**Comment by arpu** [comment]
@cabanier tested your #22074, -> i can enter again with enabled webxr Layers but the quality is very poor looks like anti alias is not working with this ( webxr layer enabled/disabled)

**Comment by arpu** [comment]
with stock threejs 130 and disables Webxr Layers in OculusBrowser the result looks fine

**Comment by cabanier** [comment]
Can you point me to a url or link to your github so I can see it?

**Comment by arpu** [comment]
only testing this local, not pushed to any repo

**Comment by cabanier** [comment]
> only testing this local, not pushed to any repo

I'm worried about this regression so let me know if you have a way to create a test case.

**Comment by arpu** [comment]
yes: i updated https://vrland.io/lobby ( v0.22.1 right top corner)  right now with your new webxr regression fix from #22074 

result: enabled webxr Layer -> webxr enter works no antialias
          disable webxr Layer -> webx enter works, antialias works

**Comment by dbradleyfl** [comment]
@cabanier @mrdoob fix confirmed on my end. Thanks @cabanier ! I tested the examples on my Oculus Quest 2 with the latest version of the dev branch. Any chance this will go out as 130.1 in the near future?

**Comment by cabanier** [comment]
I investigated this and realized that we're not exposing the multisample webgl extension. 
This means that content using layers can't have AA until we add that.

Should we pull layers support for now? Alternatively, we can disable layers if AA is requested but that seems confusing.

**Comment by cabanier** [comment]
Alternatively, we can use more of three.js' code and tell it to render to the textures using the multisampled render target. 
@Mugen87 @mrdoob I think you are more familiar with this code. Can you tell me how I can do that?

**Comment by arpu** [comment]
i think in this  Bug request we should concentrate to the "normal"  https://threejs.org/docs/#api/en/renderers/WebGLRenderer antialias  ( multisampler render target is not needed for this)

**Comment by cabanier** [comment]
> i think in this Bug request we should concentrate to the "normal" https://threejs.org/docs/#api/en/renderers/WebGLRenderer antialias ( multisampler render target is not needed for this)

The "normal" antialias uses the browser's builtin support. Unfortunately this works only if the framebuffer is under the control of the browser. With layers, the fb is created by the author so it has to make the necessary calls to make sure that it's rendering to the textures with AA.
Renderbuffers allow this but they are awkward to use. However, it seems that three.js already has logic to enable them.

The right solution is to enable the GL extension that the browser is using under the hood.

**Comment by Mugen87** [comment]
> Alternatively, we can use more of three.js' code and tell it to render to the textures using the multisampled render target.

Then we need to merge #22066 first. Otherwise it is not possible to resolve the multisampling to the default framebuffer.

**Comment by Mugen87** [comment]
> Any chance this will go out as 130.1 in the near future?

I guess the severity of the issue justifies a new minor release.

**Comment by cabanier** [comment]
We'll need to fix the anti-aliasing as well.

I will explore getting support for `EXT_multisampled_render_to_texture` as it is a much simpler and efficient way to get antialiasing on mobile GPU's

**Comment by Mugen87** [comment]
The regression should be fixed now in prod.

**Comment by arpu** [comment]
hmm but still the  antialiasing Problem with enabled Layers?

**Comment by Mugen87** [comment]
That's not part of the regression. Probably better to open a separate issue for this.

**Comment by arpu** [comment]
ok tested it right now and still a problem for latest threejs and oculusBrowser default enabled Layers ( tested with the webxr ball sample)
@cabanier  this needs to be fixed with a new OculusBrowser version?

**Comment by cabanier** [comment]
> @cabanier this needs to be fixed with a new OculusBrowser version?

It won't be fixed with a new Oculus browser version.
@Mugen87 how hard is it to apply multisampling to the layer after you fixed #22066? Does it have a performance impact?

**Comment by mrdoob** [comment]
@cabanier I'm still catching up with all this... How come we lost antialias?

**Comment by cabanier** [comment]
AA in regular WebXR is done by using [FramebufferTexture2DMultisampleEXT](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_multisampled_render_to_texture.txt) under the hood.
This extension is not (yet) available in WebGL but it is possible to have to same behavior using the GL commands that three.js is using for multisampled output.

If this is proving too hard, we can keep support for layers but revert to drawing to the `XRWebGLLayer` object that was used previously.

**Comment by mrdoob** [comment]
Hmm... So before we were using `XRWebGLLayer` and now we're using `XRWebGLBinding`.
Is this needed in order to be able to use `XRMediaBinding`?

**Comment by cabanier** [comment]
no, you can mix them.
`XRWebGLBinding` is used to create the new layer styles and `XRMediaBinding` is used to create media layers.
`XRWebGLLayer` can just be created

**Comment by Mugen87** [comment]
@Mugen87 how hard is it to apply multisampling to the layer after you fixed #22066? Does it have a performance impact?

This is something I have to find out. Meaning investigating the performance differences of default/built-in MSAA with the manual approach. BTW I have closed #22066 accidentally. I'll make a new PR as soon as the API is clear (see https://github.com/mrdoob/three.js/pull/22066#issuecomment-873206745).

**Comment by cabanier** [comment]
@mrdoob is there a time constraint?
If it takes too long, I can switch back to the old style layer.

**Comment by mrdoob** [comment]
@cabanier Then I think it'll be best to revert the changes in WebXRManager until we have a clear path to support antialias.

**Comment by cabanier** [comment]
I have a patch in progress in the Oculus browser that exposes an extension to bring AA back. (see https://github.com/cabanier/three.js/commit/9350b5a6facdd92746b59b9ad29a731801826d72#diff-a27b9d3ba68457069cc8ff521208ae9d0cc6d9256f6f48ada6316fc2d732ba7eR227)

For now, I agree that we should revert.

**Comment by mrdoob** [comment]
I see... Would you like to do the PR that reverts that part or should I give it a go?

**Comment by cabanier** [comment]
Let me try fixing it using 'renderbufferStorageMultisample'. If that doesn't work, I'll revert it.

I'm also trying to fast-track the webgl extension.

**Comment by cabanier** [comment]
#22127 will work around the AA issue until I can get the extension approved.

There is a bug in the browser that stops webgl layers from blending with other layers. This will be fixed in the oculus browser in 2 weeks.
