### ISSUE TITLE
renderDepth has no effect (WebGLRenderer & PerspectiveCamera)

### ISSUE THREAD

**Issue by electricessence** [mrdoob/three.js#5496]
I've spent a couple days working on this issue with no result.
I tried to get a jsFiddle together but couldn't get dat.gui to integrate with it in order to demonstrate changing these values with no effect.

But the simple fact is:
With a WebGLRenderer and PerspectiveCamera, any attempt at altering sorting does nothing.
I even tried hacking three.js at one point to introduce a custom sort, but apparently, it's overridden or ignored.

The sample I used is as follows:
```javascript
var gui = new dat.GUI();
var folder = gui.addFolder("renderDepth");

var R = new THREE.Mesh( new THREE.BoxGeometry(50, 50, 50), new THREE.MeshPhongMaterial({color:0xFF0000}) );
R.position.set(-10,-10,-10);
R.renderDepth = 3;
folder.add(R,"renderDepth").min(0).max(1000).step(1).name("Red").listen();
scene.add(R);

var G = new THREE.Mesh( new THREE.BoxGeometry(50, 50, 50), new THREE.MeshPhongMaterial({color:0x00FF00}) );
G.renderDepth = 2;
folder.add(G,"renderDepth").min(0).max(1000).step(1).name("Green").listen();
scene.add(G);

var B = new THREE.Mesh( new THREE.BoxGeometry(50, 50, 50), new THREE.MeshPhongMaterial({color:0x0000FF}) );
B.position.set(+10,+10,+10);
B.renderDepth = 1;
folder.add(B,"renderDepth").min(0).max(1000).step(1).name("Blue").listen();
scene.add(B);

folder.open();
```
I also noticed that very few pertinent questions on StackOverflow were answered and so I'm hoping this is enough of a bug to post this here.

**Comment by lmcd** [comment]
Is this still on the radar? Would love to see renderDepth return for r70!

**Comment by Wilt** [comment]
Yeah, it would indeed be great if `renderDepth` issues would be solved in r70

**Comment by Cubiverse** [comment]
Another vote for fixing this.

I use renderDepth for my sky systems (so a couple of large planes, existing at same height, with clouds rendered via a shader). For now I will rolling this into a single plane to get around this change.

There's also other various tricks used in games that require the the ability to set or force render depth values.

**Comment by WestLangley** [comment]
@Cubiverse There appears to be a lot of confusion about what is possible -- or should be possible -- when "setting `renderDepth`" in three.js. It would be helpful if you would provide a live link to demonstrate your use case, and explain exactly what you believe should be happening that is not.

Are you interested in setting a custom `renderDepth` so an object will be rendered "in front" when it is not, or so an object will be rendered _correctly_, when it is not?

> There's also other various tricks used in games that require the the ability to set or force render depth values.

Which ones are you referring to?

Ditto  @lmcd  @Wilt

**Comment by Wilt** [comment]
http://stackoverflow.com/questions/22348252/threejs-how-to-set-rendering-order-of-materials-of-overlapping-meshes

I think it might be because of additional transparency. But I tried different things and can't seem to get it to work. I will add a fiddle as soon as I have some time.

**Comment by Cubiverse** [comment]
@WestLangley - my use case can be seen at http://game.cubiverse.net/17 (use any username) - When you are in-game look at the sky, each cloud layer is a plane located at the same X,Y,Z.. in order to get this to extend to the horizon I need a massive plane. Now for whatever reason (it was years ago) I found that I couldn't position them correctly due to Z-fighting (even with a gap) and I had to resort to the renderDepth "fix".

I have fixed this now by using a single mesh and just upgrading the shader to draw multiple cloud layers (an optimise I'd been putting off).. 

I've used this trick a few times over the last decade but I forget exactly why (new code pushes old code out of my brain ;)

I do think however anything that has to be executed "per object per frame" is less than optimal, so maybe other's can engineer it out instead of adding another test and set in the three.js render loop.

**Comment by valette** [comment]
@WestLangley here is an other example : http://jsfiddle.net/Locd5rha/
In this scene, a red cube contains a green and blue cube, all transparent.

The green and blue cubes are not visible in all positions. 
This was easily fixable using renderDepth

**Comment by WestLangley** [comment]
> This was easily fixable using renderDepth

@valette Can you create another version of your fiddle to show what you would have done in the past to make the green and blue cubes "visible in all positions"?

**Comment by valette** [comment]
@WestLangley  http://jsfiddle.net/2um4Lg5h/
the fix is in line 35, you can comment it so see the bug

**Comment by lmcd** [comment]
I'm building a 2D interface in three.js using many overlapping planes at the same `z` position. The order of these planes changes frequently, and I'm using `renderDepth` to achieve this. No, I can't use Canvas 2D, as there is a big dependancy on shaders and various 3D things happening :)

Since first commenting on this issue, I'm now working on another three.js project for an enormous tech client doing very similar things. Again, we've hit the issue with `renderDepth` being broken.

**Comment by WestLangley** [comment]
@lmcd I am trying to elicit how users are using this feature. Can you please answer some questions?

Are you setting `renderDepth` for all objects, or just some of them?
Are your objects opaque, transparent, or a mix?
Are you using the same material for all objects?
Are you changing the default value of `depthTest`?
Are you changing the default value of `depthWrite`?
Are you setting `renderDepth` so something renderers correctly, or so something is rendered "in front", "or behind"?
Are you setting `renderDepth` to force something to be in front of something else, or to force something to be in front of _everything_ else?

Thanks.

> Again, we've hit the issue with renderDepth being broken.

I you create a simple demo to demonstrate the problem for the 2nd client, I'd like to see it.

**Comment by WestLangley** [comment]
@valette Again, I am trying to understand the user's issues. This is why I am asking questions.

> the fix is in line 35

You set `renderDepth` and it appears to "work". So what do you feel is wrong with the current version of the library?

> you can comment it so see the bug

If you comment out the line, `renderDepth` is not set at all. What is the "bug"?

**Comment by valette** [comment]
yes, sorry, that was a bit unclear...
Here is the example (two rotating cubes) with r69:
http://jsfiddle.net/9euthomy/
both cubes are transparent, one inside the other one. The inside cube is visible only from time to time due to the rotation. Un-commenting line 35 fixes this.

Here is the same  example, with r70:
http://jsfiddle.net/8v8u3gqc/

**Comment by WestLangley** [comment]
Oops. Sorry, everybody, I did not realize that `renderDepth` has been removed in r70.

Personally, I did not like this feature, because it did not allow the user to "set the render depth" at all. It only had an effect on sorting. Furthermore, `renderDepth` was a quantity in clip-space -- an unintuitive space for users.

An alternate method is to use multiple render passes -- render one scene followed by another one. This may be made easier soon with the introduction of "layers".

Another solution is `render.sortObjects = false`, where objects are rendered in the order they appear in the scene graph.

**Comment by Cubiverse** [comment]
I found another instance in my game where this problem occurs, the sea is a large transparent mesh causing plants or transparent cubes to (sometimes) render black behind them if the sea is rendered after the plants (as the plane is so large, the z order can't be calculated correctly hence renderDepth was used)

![zorderbug](https://cloud.githubusercontent.com/assets/9885330/6189153/52d4ed66-b390-11e4-9248-ed90d71164d5.png)

I may look at multiple render passes, but the issue then becomes a "user" one when it's a feature that is present in the majority of 3D engines for these exact use-case situations.

**Comment by WestLangley** [comment]
@Cubiverse So you were forcing one mesh to render as the very _first (or last)_ transparent object by setting `renderDepth` for _that mesh only_. Is that correct? What value did you use for `renderDepth` in that case?

> it's a feature that is present in the majority of 3D engines for these exact use-case situations.

Can you please identify the engines you are referring to -- and provide a link to the feature, if available?

**Comment by mrdoob** [comment]
How about being able to change the sorting function in the renderer?

```javascript
var customOpaqueSort = function () {

	if ( a.userData.priority !== b.userData.priority ) {

		return a.userData.priority - b.userData.priority;

	} else if ( a.material.id !== b.material.id ) {

		return a.material.id - b.material.id;

	} else if ( a.z !== b.z ) {

		return a.z - b.z;

	} else {

		return a.id - b.id;

	}

};

renderer.setOpaqueSort( customOpaqueSort );
```

**Comment by mrdoob** [comment]
Or maybe we can add a `renderOrder` property (default to `0`.

```javascript
cube.renderOrder = 1;
```

**Comment by WestLangley** [comment]
If you want to sort by material, you need to sort by shader, not material `id`. No?

If we implement "layers", we can support a similar functionality to what is requested here -- although it would require multiple render passes. Also, the same can be achieved with multiple scenes.

**Comment by mrdoob** [comment]
> If you want to sort by material, you need to sort by shader, not material `id`. No?

Good point! I should change that. That's how the current sorting code looks like.

> If we implement "layers", we can support a similar functionality to what is requested here -- although it would require multiple render passes. Also, the same can be achieved with multiple scenes.

The `renderOrder` approach will result in this sorting function:

```javascript
function painterSortStable ( a, b ) {

	if ( a.renderOrder !== b.renderOrder ) {

		return a.renderOrder - b.renderOrder;

	} else if ( a.material.id !== b.material.id ) {

		return a.material.id - b.material.id;

	} else if ( a.z !== b.z ) {

		return a.z - b.z;

	} else {

		return a.id - b.id;

	}

}
```

This rescues the previous `renderDepth` but in a more logical way. The problem before was that `renderDepth` would overwrite `a.z` or `b.z`. That was fine until sorting by material was implemented.

**Comment by WestLangley** [comment]
That looks fine to me -- as long as `a.material.id` means `a.material.shader.id`. : - )

I certainly like setting render order better than setting render depth.

**Comment by mrdoob** [comment]
> That looks fine to me -- as long as `a.material.id` means `a.material.shader.id`. : - )

Turns out `a.material.program` can be not available at sort time. So I'll leave that for another time...

**Comment by mrdoob** [comment]
Oks. The newly added `.renderOrder` should solve this one.

**Comment by tmullen71** [comment]
I'm unable to get .renderOrder to have any effect. 

http://jsfiddle.net/tmullen71/qs5wz9qt/

Although the objects are set to renderOrder values 1 and 2 respectively, they render in order of depth. 

Am I using this correctly, or is there still an issue with this feature?

Thanks!

**Comment by WestLangley** [comment]
@tmullen71 As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

http://stackoverflow.com/questions/30407288/using-renderorder-in-three-js/30408704#30408704

**Comment by tmullen71** [comment]
Sorry about that. Thanks for the link.
