### ISSUE TITLE
VRMLLoader: Object is not rendering in scene

### ISSUE THREAD

**Issue by Priyank30** [mrdoob/three.js#9514]
I am trying to load object using VRMLoader but nothing is displaying on screen. I have attached sample vrml file. The given below image which is taken from cad sofware(KiCad) using the same vrml file and I can see the capacitor so I think the file is ok.

Would you please help me out to sortout this issue? I'm stuck at this point.

@bartmcleod, @mrdoob 

![cap](https://cloud.githubusercontent.com/assets/2055200/17666080/271697be-631c-11e6-8531-302d9f931b0b.png)

[cap.zip](https://github.com/mrdoob/three.js/files/418121/cap.zip)

**Comment by bartmcleod** [comment]
I can look into this. Have you tried the new VrmlParser on your model?
To use it: `npm install vrmlparser`

https://github.com/bartmcleod/VrmlParser

**Comment by bartmcleod** [comment]
The first thing that comes up is that the Switch node is not yet supported by VrmlParser.Renderer.ThreeJs. This should not necessarily lead to a black scene though, so I will try to fix that first and then look into adding support for the Switch node.

**Comment by bartmcleod** [comment]
I fixed the issue where having `children Switch {}` would lead to false being added to the scene. Please note that this is only updated in VrmlParser. It is not an issue with ThreeJs. It still leads to a black scene in your case, because the Switch is not yet parsed. I will look into that next.

**Comment by bartmcleod** [comment]
Ok, so now VrmlParser supports the Switch node, but this brings me to the next issue, which might or might not have something to do with your file.

**Comment by Priyank30** [comment]
@bartmcleod 
Thanks for your quick response. I have download your project and insted of run npm I have added threjs folder and add required files to run example.html. 
Default **example.wrl** is working but still not able to load **cap.wrl**. It gives me error something like below. I have also attached your project set up that I have configured in local.
Would you look into this? Please correct me if I'm doing something wrong.

![error](https://cloud.githubusercontent.com/assets/2055200/17695356/cc29306e-63c5-11e6-80a7-4ca5be1ff17c.png)

[VrmlParser-master.zip](https://github.com/mrdoob/three.js/files/419953/VrmlParser-master.zip)

**Comment by bartmcleod** [comment]
@Priyank30 Thanks for bringing this up!
I am currently at the exact same stage as yourself, encountering the same error. This occurs in one of the more difficult parts in the code and it has my attention, but I can't work on it right now. If you want to work your way through it, you could manually edit the VRML file and simplify it until it works. That way, you will have pinpointed the problem and you might be able to tell if your software did something wrong when it exported the VRML. This however, is not very likely.

Like I said, it has my attention and I will look into it as soon as I can.

**Comment by Priyank30** [comment]
Thanks for your update. Looking forward for your next update till then I will try myself what I can do or atleast try to find something that can help you.

**Comment by bartmcleod** [comment]
From what I found in the code, it looks like your model has faces defined, for which no vertices are present. While I can imagine that KiCad tolerates this or even causes this, threejs assumes that no faces can be defined if no vertices are present. My idea comes from this piece of code in Three:
```	computeFaceNormals: function () {

		var cb = new THREE.Vector3(), ab = new THREE.Vector3();

		for ( var f = 0, fl = this.faces.length; f < fl; f ++ ) {

			var face = this.faces[ f ];

			var vA = this.vertices[ face.a ];
			var vB = this.vertices[ face.b ];
			var vC = this.vertices[ face.c ];

			cb.subVectors( vC, vB );
			ab.subVectors( vA, vB );
			cb.cross( ab );

			cb.normalize();

			face.normal.copy( cb );

		}

	},
```
As you can see, it loops over the faces and then finds their corresponding vertices by index. The vertices are then passed to `subvectors`, which receives `undefined` and errors out. In order to prevent the problem from inside the VrmlParser.Renderer.ThreeJs, we could detect this and not add faces that have missing vertices.

**Comment by bartmcleod** [comment]
While analyzing this it appears in the messages that I am logging that there is something wrong in my loop. I get indexes with values of 11,0 and 12,3 which are obviously invalid. To be continued.

**Comment by bartmcleod** [comment]
I found an error with parsing integers (!) in the VRML grammar and fixed that. It still does not solve the loading of the scene (Chrome hangs on errors with the bounding shpere I think), but at least your coordIndex appears to be parsed correctly now.

**Comment by bartmcleod** [comment]
Another thing I found is that your file contains IndexedLineSet, which is not yet supported. I should like to add it, but it will not be before next week. I do think the errors I am currently seeing are related to this, because they occur because of a Shape that does have the correct Material, but does have false for geometry, which should have been IndexedLineSet. Thanks for being patient an helping to improve the VrmlParser.

**Comment by Priyank30** [comment]
Looking forward for your update. Thanks for your support.

**Comment by bartmcleod** [comment]
We now have support for IndexedLineSet, but the `cap.wrl` still shows errors when I try to load it. I will investigate further.

**Comment by bartmcleod** [comment]
There is another unsupported node in your file: PointSet. I should add support for that too an see what we get next.

**Comment by bartmcleod** [comment]
We now have very limited support for PointSet and if you update, you can load the capacitor wrl. The PointSet is not yet visible, because no proper representation is added for it. All that is currently done is that the points are added as vertices for a geometry, which is then renderered as if it were a Mesh. However, this does not prevent you from seeing the capacitor.

**Comment by bartmcleod** [comment]
@mrdoob I think the issue can be closed.

**Comment by Priyank30** [comment]
@bartmcleod I found some few more bugs and I think they are introduced in last update. I have attached wrl file for your simulation and shows issues in image.

![issue](https://cloud.githubusercontent.com/assets/2055200/17889760/2fe98164-6932-11e6-8fc3-e90781bf5971.png)

[LED-0805.zip](https://github.com/mrdoob/three.js/files/432251/LED-0805.zip)

**Comment by bartmcleod** [comment]
@Priyank30 Awesome! It's great to see that you are now contributing by challenging the parser and the renderer. To not pollute the three.js repository, we would best move to https://github.com/bartmcleod/VrmlParser, since these issues actually belong there now.

I will look into the new files you provided. In the meantime, I have pushed a new update, which uses a custom shader for a PointSet, which projects the points with a fixed size of 3.0 pixels. This means they are slightly better visible than 1 pixel size, but they do not block the view on your object and your capacitor renders nicely.

From the screenshots you have taken I think it might already help if you turn off shadows in the example.html, but that's just a thought not backed by investigation.

So, let's continue this in the proper repository. I'm looking forward to the next challenge.

**Comment by Priyank30** [comment]
Thanks for notifying me. I will post new issue on your repository and will continue further fix there.
